#!/bin/bash
# THIS FILE IS GENERATED BY tools/setup_python.sh
export PYTHONUSERBASE="/data2/qt/MusicGeneration/tools/python_user_base"
export PATH="/data2/qt/MusicGeneration/tools/python_user_base/bin":${PATH}
export PATH=/opt/conda/bin:${PATH}
